### ISSUE TITLE
Class 'Isolated\Symfony\Component\Finder\Finder' not found

### ISSUE THREAD

**Issue by calind** [humbug/php-scoper#349]
**This bug does not affect versions lower than 0.12.0.**

## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 0.12.x
| PHP version | 7.3.7
| Platform with version | MacOS

<details>
 <summary>scoper.inc.php</summary>
 
 ```php
 <?php
 
 declare(strict_types=1);
 
 use Isolated\Symfony\Component\Finder\Finder;
 
 return [
    'finders' => [
        Finder::create()->files()->in('src'),
    ],
 ];

 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ php-scoper add-prefix
PHP Fatal error:  Uncaught Error: Class 'Isolated\Symfony\Component\Finder\Finder' not found in /Users/calin/work/src/github.com/presslabs/stack-mu-plugin/scoper.inc.php:17
Stack trace:
#0 phar:///usr/local/bin/php-scoper/src/Configuration.php(58): include()
#1 phar:///usr/local/bin/php-scoper/src/Console/Command/AddPrefixCommand.php(205): _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Configuration::load('/Users/calin/wo...')
#2 phar:///usr/local/bin/php-scoper/src/Console/Command/AddPrefixCommand.php(57): _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Console\Command\AddPrefixCommand->retrieveConfig(Object(_HumbugBox1e6e23f5a88c\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox1e6e23f5a88c\Symfony\Component\Console\Output\ConsoleOutput), Object(_HumbugBox1e6e23f5a88c\Symfony\Component\Console\Style\SymfonyStyle))
#3 phar:///usr/local/bin/php-scoper/vendor/symfony/console/Command/Command.php(127): _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Console\Command\AddPrefixCommand->execute(Object(_HumbugBox1e6e23f5a88c\Symfony\Component\Co in /Users/calin/work/src/github.com/presslabs/stack-mu-plugin/scoper.inc.php on line 17

Fatal error: Uncaught Error: Class 'Isolated\Symfony\Component\Finder\Finder' not found in /Users/calin/work/src/github.com/presslabs/stack-mu-plugin/scoper.inc.php on line 17

Error: Class 'Isolated\Symfony\Component\Finder\Finder' not found in /Users/calin/work/src/github.com/presslabs/stack-mu-plugin/scoper.inc.php on line 17

Call Stack:
    0.0010     397968   1. {main}() /usr/local/bin/php-scoper:0
    0.0202    1096160   2. require('phar:///usr/local/bin/php-scoper/bin/php-scoper') /usr/local/bin/php-scoper:19
    0.0479    6620424   3. _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Console\Application->run() phar:///usr/local/bin/php-scoper/bin/php-scoper:44
    0.0553    6851432   4. _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Console\Application->doRun() phar:///usr/local/bin/php-scoper/vendor/symfony/console/Application.php:101
    0.0556    6854808   5. _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Console\Application->doRunCommand() phar:///usr/local/bin/php-scoper/vendor/symfony/console/Application.php:190
    0.0556    6854808   6. _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Console\Command\AddPrefixCommand->run() phar:///usr/local/bin/php-scoper/vendor/symfony/console/Application.php:586
    0.0558    6856528   7. _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Console\Command\AddPrefixCommand->execute() phar:///usr/local/bin/php-scoper/vendor/symfony/console/Command/Command.php:127
    0.0568    7006096   8. _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Console\Command\AddPrefixCommand->retrieveConfig() phar:///usr/local/bin/php-scoper/src/Console/Command/AddPrefixCommand.php:57
    0.0573    7063576   9. _HumbugBox1e6e23f5a88c\Humbug\PhpScoper\Configuration::load() phar:///usr/local/bin/php-scoper/src/Console/Command/AddPrefixCommand.php:205
    0.0574    7067272  10. include('/Users/calin/work/src/github.com/presslabs/stack-mu-plugin/scoper.inc.php') phar:///usr/local/bin/php-scoper/src/Configuration.php:58
 ```
</details>

**Comment by polevaultweb** [comment]
I've just encountered this using the 0.13.0 Phar too.

**Comment by theofidry** [comment]
Do you have a reproducer by any chance?

**Comment by polevaultweb** [comment]
@theofidry sorry! 

| Question    | Answer
| ------------| ---------------
| Box version | 0.13.0 
| PHP version | 7.2.1
| Platform with version | MacOS


<details>
 <summary>scoper.inc.php</summary>
 
 ```php
 <?php

declare(strict_types=1);

use Isolated\Symfony\Component\Finder\Finder;

return [
   'finders' => [
       Finder::create()->files()->in('src'),
   ],
];

 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ PHAR_URL="https://github.com/humbug/php-scoper/releases/download/0.13.0/php-scoper.phar"
$ curl -O -L $PHAR_URL
 
$ php ./php-scoper.phar add-prefix
 > output
[07-Jan-2020 12:35:54 UTC] PHP Fatal error:  Uncaught Error: Class 'Isolated\Symfony\Component\Finder\Finder' not found in /Applications/MAMP/htdocs/my-site/wp-content/plugins/my-plugin/build/scoper.inc.php:14
Stack trace:
#0 phar:///Applications/MAMP/htdocs/my-site/wp-content/plugins/my-plugin/build/php-scoper.phar/src/Configuration.php(58): include()
#1 phar:///Applications/MAMP/htdocs/my-site/wp-content/plugins/my-plugin/build/php-scoper.phar/src/Console/Command/AddPrefixCommand.php(205): _HumbugBox1b62df0e3880\Humbug\PhpScoper\Configuration::load('/Applications/M...')
#2 phar:///Applications/MAMP/htdocs/my-site/wp-content/plugins/my-plugin/build/php-scoper.phar/src/Console/Command/AddPrefixCommand.php(57): _HumbugBox1b62df0e3880\Humbug\PhpScoper\Console\Command\AddPrefixCommand->retrieveConfig(Object(_HumbugBox1b62df0e3880\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox1b62df0e3880\Symfony\Component\Console\Output\ConsoleOutput), Object(_HumbugBox1b62df0e3880\Symfony\Component\Console in /Applications/MAMP/htdocs/my-site/wp-content/plugins/my-plugin/build/scoper.inc.php on line 14
 ```
</details>

**Comment by theofidry** [comment]
I meant more a repository where I could reproduce it, because there is an end-to-end test in the repository and I can't reproduce it there

**Comment by polevaultweb** [comment]
@theofidry here you go https://github.com/polevaultweb/php-scoper-phar-issue :)

**Comment by theofidry** [comment]
Thanks, will try to check it out ASAP

**Comment by polevaultweb** [comment]
@theofidry I opened a new issue so we can keep tracking it https://github.com/humbug/php-scoper/issues/368
