### ISSUE TITLE
Error while trying to dump autoload after successful prefixing

### ISSUE THREAD

**Issue by noknokcody** [humbug/php-scoper#448]
Hi there, I'm getting the following error when trying to dump my composer autoloader after successful prefixing.

Here's my terminal output

``` bash
    ____  __  ______     _____
   / __ \/ / / / __ \   / ___/_________  ____  ___  _____
  / /_/ / /_/ / /_/ /   \__ \/ ___/ __ \/ __ \/ _ \/ ___/
 / ____/ __  / ____/   ___/ / /__/ /_/ / /_/ /  __/ /
/_/   /_/ /_/_/       /____/\___/\____/ .___/\___/_/
                                     /_/

PHP Scoper version 0.13.10@e56b0d9

 7512/7512 [============================] 100%


 [OK] Successfully prefixed 7512 files.


 // Memory usage: 78.92MB (peak: 178.12MB), time: 2983.14s


Cody Rees@DESKTOP-CODY MINGW64 /c/_noknok-studios/docker-projects/docker.woocommercesandbox.local/sites/localhost/html/wp-content/plugins/noknok-woo-marketing-platform (master)
$

Cody Rees@DESKTOP-CODY MINGW64 /c/_noknok-studios/docker-projects/docker.woocommercesandbox.local/sites/localhost/html/wp-content/plugins/noknok-woo-marketing-platform (master)
$ composer dump-autoload -o --working-dir build

Fatal error: Uncaught Error: Class 'ComponentInstaller\Installer' not found in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php:219
Stack trace:
#0 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php(390): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), false, false)
#1 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php(86): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository), false)     
#2 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php(404): Composer\Plugin\PluginManager->loadInstalledPlugins()
#3 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Factory.php(595): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, false)
#4 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php(408): Composer\Factory::create( in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Plugin/PluginManager.php on line 219

```

My scoper.inc.php
``` php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Isolated\Symfony\Component\Finder\Finder;

use pxlrbt\PhpScoper\PrefixRemover\IdentifierExtractor;
use pxlrbt\PhpScoper\PrefixRemover\RemovePrefixPatcher;

$identifiers = (new IdentifierExtractor())
    ->addStub('vendor/php-stubs/wordpress-stubs/wordpress-stubs.php')
    ->addStub('vendor/paulthewalton/acf-pro-stubs/acf-pro-stubs.php')
    ->extract();

return [
    'prefix' => 'WMPLibs',

    'finders' => [
        Finder::create()->files()
            ->in('src')
            ->in('templates'),
        Finder::create()
            ->files()
            ->ignoreVCS(true)
            ->notName('/LICENSE|.*\\.md|.*\\.dist|Makefile|composer\\.json|composer\\.lock/')
            ->exclude([
                'doc',
                'test',
                'test_old',
                'tests',
                'Tests',
                'vendor-bin',
            ])
            ->in('vendor'),
        Finder::create()->append([
            'noknok-wmp-functions.php',
            'noknok-wmp-plugin.php',
            'composer.json'
        ]),
    ],

    'patchers' => [
        ( new RemovePrefixPatcher( $identifiers ) ),
    ],

    'whitelist-global-constants' => true,
    'whitelist-global-classes' => true,
    'whitelist-global-functions' => true,
];
```

Running dump-autoload on the main project works perfectly fine it's just the scoped build files that seem to error out.

Any help is greatly appreciated!

**Comment by noknokcody** [comment]
Okay so I've sorted it. 

I'm not going to pretend in the slightest I know how composer works here but it looks like I had some composer plugins responsible for deploying assets on autoload. These plugins were getting prefixed in composers installed.json file so I'm going to assume composer got confused due to not being able to load the prefixed classes during the dump-autoload process.

Updating my scoper-inc.php to whitelist the namespace of these plugins fixed this for me.
``` PHP
    'whitelist' => [
        'ComponentInstaller\*',
        'Assetic\*'
    ],
```
