### ISSUE TITLE
PHP-Scoper does not work with PHP 8.1

### ISSUE THREAD

**Issue by sebastianbergmann** [humbug/php-scoper#530]
From https://github.com/sebastianbergmann/phpunit/runs/3131376699:

```
    ____  __  ______     _____
   / __ \/ / / / __ \   / ___/_________  ____  ___  _____
  / /_/ / /_/ / /_/ /   \__ \/ ___/ __ \/ __ \/ _ \/ ___/
 / ____/ __  / ____/   ___/ / /__/ /_/ / /_/ /  __/ /
/_/   /_/ /_/_/       /____/\___/\____/ .___/\___/_/
                                     /_/

PHP Scoper version 0.15.0 2021-05-10 21:02:42 UTC



 // Memory usage: 14.82MB (peak: 23.42MB), time: 0.06s                          

 1280/1280 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
In AddPrefixCommand.php line 118:
                                                                               
  Could not parse the file "/home/runner/work/phpunit/phpunit/build/tmp/phar/  
  doctrine-instantiator/Doctrine/Instantiator/Instantiator.php".               
                                                                               

In Lexer.php line 197:
                           
  Undefined array key 288  
                           

add-prefix [-d|--working-dir WORKING-DIR] [-p|--prefix PREFIX] [-o|--output-dir OUTPUT-DIR] [-f|--force] [-s|--stop-on-failure] [-c|--config CONFIG] [--no-config] [--] [<paths>...]
```

On my local machine I get:
```
Deprecated: Return type of HumbugBox3100\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/php-scoper/.box/src/RequirementCollection.php on line 12

Deprecated: Return type of HumbugBox3100\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/php-scoper/.box/src/RequirementCollection.php on line 16

Fatal error: During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of _HumbugBox3a809f886aa2\Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/php-scoper/vendor/symfony/finder/Finder.php:220
Stack trace:
#0 phar:///usr/local/src/phpunit/tools/php-scoper/vendor/symfony/finder/Finder.php(17): _HumbugBox3a809f886aa2\Humbug\PhpScoper\{closure}(8192, 'Return type of ...', 'phar:///usr/loc...', 220)
#1 phar:///usr/local/src/phpunit/tools/php-scoper/.box/vendor/composer/ClassLoader.php(444): include('phar:///usr/loc...')
#2 phar:///usr/local/src/phpunit/tools/php-scoper/.box/vendor/composer/ClassLoader.php(444): include('phar:///usr/loc...')
#3 phar:///usr/local/src/phpunit/tools/php-scoper/.box/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///usr/loc...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('_HumbugBox3a809...')
#5 phar:///usr/local/src/phpunit/tools/php-scoper/bin/php-scoper(42): class_alias('_HumbugBox3a809...', 'Isolated\\Symfon...')
#6 /usr/local/src/phpunit/tools/php-scoper(19): require('phar:///usr/loc...')
#7 /usr/local/src/phpunit/tools/php-scoper(19): require('phar:///usr/loc...')
#8 {main} in phar:///usr/local/src/phpunit/tools/php-scoper/vendor/symfony/finder/Finder.php on line 17
```

Here is the full output of running `ant phar-nightly` for PHPUnit's current state of `master`:

```
$ ant phar-nightly
Buildfile: /usr/local/src/phpunit/build.xml

clean:
   [delete] Deleting directory /usr/local/src/phpunit/build/artifacts
   [delete] Deleting directory /usr/local/src/phpunit/vendor
   [delete] Deleting: /usr/local/src/phpunit/composer.lock

-dependencies-installed:

validate-composer-json:
 [composer] 
 [composer] Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
 [composer] Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/src/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
 [composer] Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/Repository/ArrayRepository.php:286
 [composer] Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/Repository/WritableArrayRepository.php:286
 [composer] Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/Repository/InstalledFilesystemRepository.php:286
 [composer] Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/src/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
 [composer] Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/src/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
 [composer] Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/src/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
 [composer] Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/src/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
 [composer] /usr/local/src/phpunit/composer.json is valid
 [composer] Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/src/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48

install-dependencies:
 [composer] Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/src/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
 [composer] Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/Repository/ArrayRepository.php:286
 [composer] Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/Repository/WritableArrayRepository.php:286
 [composer] Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/Repository/InstalledFilesystemRepository.php:286
 [composer] Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///usr/local/src/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
 [composer] Loading composer repositories with package information
 [composer] 
 [composer] Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\Pool::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Pool.php:82
 [composer] Updating dependencies
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\RuleSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/RuleSet.php:119
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\RuleSet::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/RuleSet.php:101
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::current() should either be compatible with Iterator::current(): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Decisions.php:155
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::next() should either be compatible with Iterator::next(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Decisions.php:165
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::key() should either be compatible with Iterator::key(): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Decisions.php:160
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::valid() should either be compatible with Iterator::valid(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Decisions.php:170
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::rewind() should either be compatible with Iterator::rewind(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Decisions.php:150
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\Decisions::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/Decisions.php:145
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::current() should either be compatible with Iterator::current(): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/RuleSetIterator.php:36
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::next() should either be compatible with Iterator::next(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/RuleSetIterator.php:46
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::key() should either be compatible with Iterator::key(): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/RuleSetIterator.php:41
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::valid() should either be compatible with Iterator::valid(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/RuleSetIterator.php:89
 [composer] Deprecation Notice: Return type of Composer\DependencyResolver\RuleSetIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/DependencyResolver/RuleSetIterator.php:70
 [composer] Lock file operations: 26 installs, 0 updates, 0 removals
 [composer]   - Locking doctrine/instantiator (1.4.0)
 [composer]   - Locking myclabs/deep-copy (1.10.2)
 [composer]   - Locking nikic/php-parser (v4.12.0)
 [composer]   - Locking phar-io/manifest (2.0.3)
 [composer]   - Locking phar-io/version (3.1.0)
 [composer]   - Locking phpunit/php-code-coverage (dev-master 960c5fa)
 [composer]   - Locking phpunit/php-file-iterator (dev-master a6b44af)
 [composer]   - Locking phpunit/php-invoker (dev-master d9704ef)
 [composer]   - Locking phpunit/php-text-template (dev-master ed5dfb8)
 [composer]   - Locking phpunit/php-timer (dev-master 298053f)
 [composer]   - Locking sebastian/cli-parser (dev-master 0d819bd)
 [composer]   - Locking sebastian/code-unit (dev-master fd581e1)
 [composer]   - Locking sebastian/code-unit-reverse-lookup (dev-master 2ae9c39)
 [composer]   - Locking sebastian/comparator (dev-master 67b5fcc)
 [composer]   - Locking sebastian/complexity (dev-master c1a9291)
 [composer]   - Locking sebastian/diff (dev-master 2695b4f)
 [composer]   - Locking sebastian/environment (dev-master a88ed31)
 [composer]   - Locking sebastian/exporter (dev-master 4a6270b)
 [composer]   - Locking sebastian/global-state (dev-master 61b6f14)
 [composer]   - Locking sebastian/lines-of-code (dev-master ac8ef57)
 [composer]   - Locking sebastian/object-enumerator (dev-master e84cba9)
 [composer]   - Locking sebastian/object-reflector (dev-master 1f095ab)
 [composer]   - Locking sebastian/recursion-context (dev-master fd947d7)
 [composer]   - Locking sebastian/type (dev-master 725c920)
 [composer]   - Locking sebastian/version (dev-master f5d0ef5)
 [composer]   - Locking theseer/tokenizer (1.2.0)
 [composer] Writing lock file
 [composer] Installing dependencies from lock file (including require-dev)
 [composer] Package operations: 26 installs, 0 updates, 0 removals
 [composer]   - Installing doctrine/instantiator (1.4.0): Extracting archive
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Finder.php:675
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Finder.php:732
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:85
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:113
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:65
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/FilterIterator.php:30
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\DepthRangeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/DepthRangeFilterIterator.php:41
 [composer]   - Installing myclabs/deep-copy (1.10.2): Extracting archive
 [composer]   - Installing phar-io/version (3.1.0): Extracting archive
 [composer]   - Installing phar-io/manifest (2.0.3): Extracting archive
 [composer]   - Installing theseer/tokenizer (1.2.0): Extracting archive
 [composer]   - Installing sebastian/version (dev-master f5d0ef5): Extracting archive
 [composer]   - Installing nikic/php-parser (v4.12.0): Extracting archive
 [composer]   - Installing sebastian/lines-of-code (dev-master ac8ef57): Extracting archive
 [composer]   - Installing sebastian/environment (dev-master a88ed31): Extracting archive
 [composer]   - Installing sebastian/complexity (dev-master c1a9291): Extracting archive
 [composer]   - Installing sebastian/code-unit-reverse-lookup (dev-master 2ae9c39): Extracting archive
 [composer]   - Installing phpunit/php-text-template (dev-master ed5dfb8): Extracting archive
 [composer]   - Installing phpunit/php-file-iterator (dev-master a6b44af): Extracting archive
 [composer]   - Installing phpunit/php-code-coverage (dev-master 960c5fa): Extracting archive
 [composer]   - Installing phpunit/php-invoker (dev-master d9704ef): Extracting archive
 [composer]   - Installing phpunit/php-timer (dev-master 298053f): Extracting archive
 [composer]   - Installing sebastian/cli-parser (dev-master 0d819bd): Extracting archive
 [composer]   - Installing sebastian/code-unit (dev-master fd581e1): Extracting archive
 [composer]   - Installing sebastian/recursion-context (dev-master fd947d7): Extracting archive
 [composer]   - Installing sebastian/exporter (dev-master 4a6270b): Extracting archive
 [composer]   - Installing sebastian/diff (dev-master 2695b4f): Extracting archive
 [composer]   - Installing sebastian/comparator (dev-master 67b5fcc): Extracting archive
 [composer]   - Installing sebastian/object-reflector (dev-master 1f095ab): Extracting archive
 [composer]   - Installing sebastian/global-state (dev-master 61b6f14): Extracting archive
 [composer]   - Installing sebastian/object-enumerator (dev-master e84cba9): Extracting archive
 [composer]   - Installing sebastian/type (dev-master 725c920): Extracting archive
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/FilenameFilterIterator.php:28
 [composer] Deprecation Notice: Return type of Composer\Repository\CompositeRepository::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/src/Composer/Repository/CompositeRepository.php:180
 [composer] 2 package suggestions were added by new dependencies, use `composer suggest` to see details.
 [composer] Generating optimized autoload files
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php:42
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:55
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:71
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:76
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with Iterator::rewind(): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php:30
 [composer] Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/composer/vendor/symfony/finder/Iterator/PathFilterIterator.php:27
 [composer] 23 packages you are using are looking for funding.
 [composer] Use the `composer fund` command to find out more!

-phar-prepare:
    [mkdir] Created dir: /usr/local/src/phpunit/build/artifacts
    [mkdir] Created dir: /usr/local/src/phpunit/build/tmp/phar
    [mkdir] Created dir: /usr/local/src/phpunit/build/tmp/phar-scoped
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar
     [copy] Copying 3 files to /usr/local/src/phpunit/build/tmp/phar/schema
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/php-code-coverage
     [copy] Copying 103 files to /usr/local/src/phpunit/build/tmp/phar/php-code-coverage
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/php-file-iterator
     [copy] Copying 3 files to /usr/local/src/phpunit/build/tmp/phar/php-file-iterator
     [copy] Copying 4 files to /usr/local/src/phpunit/build/tmp/phar/php-invoker
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/php-text-template
     [copy] Copying 4 files to /usr/local/src/phpunit/build/tmp/phar/php-text-template
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/php-timer
     [copy] Copying 6 files to /usr/local/src/phpunit/build/tmp/phar/php-timer
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-cli-parser
     [copy] Copying 6 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-cli-parser
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-code-unit
     [copy] Copying 16 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-code-unit
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-code-unit-reverse-lookup
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-code-unit-reverse-lookup
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-comparator
     [copy] Copying 17 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-comparator
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-complexity
     [copy] Copying 8 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-complexity
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-diff
     [copy] Copying 16 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-diff
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-environment
     [copy] Copying 3 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-environment
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-exporter
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-exporter
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-global-state
     [copy] Copying 6 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-global-state
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-lines-of-code
     [copy] Copying 7 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-lines-of-code
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/object-enumerator
     [copy] Copying 3 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-object-enumerator
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/object-reflector
     [copy] Copying 3 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-object-reflector
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-recursion-context
     [copy] Copying 3 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-recursion-context
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-type
     [copy] Copying 19 files to /usr/local/src/phpunit/build/tmp/phar/sebastian-type
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-version
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/sebastian-version
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/doctrine-instantiator
     [copy] Copying 5 files to /usr/local/src/phpunit/build/tmp/phar/doctrine-instantiator
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/myclabs-deep-copy
     [copy] Copying 25 files to /usr/local/src/phpunit/build/tmp/phar/myclabs-deep-copy
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/nikic-php-parser
     [copy] Copying 242 files to /usr/local/src/phpunit/build/tmp/phar/nikic-php-parser
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/phar-io-manifest
     [copy] Copying 50 files to /usr/local/src/phpunit/build/tmp/phar/phar-io-manifest
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/phar-io-version
     [copy] Copying 19 files to /usr/local/src/phpunit/build/tmp/phar/phar-io-version
     [copy] Copying 1 file to /usr/local/src/phpunit/build/tmp/phar/theseer-tokenizer
     [copy] Copying 8 files to /usr/local/src/phpunit/build/tmp/phar/theseer-tokenizer

phar-nightly:

-phar-determine-version:

-phar-build:
     [copy] Copying 671 files to /usr/local/src/phpunit/build/tmp/phar/phpunit

-phar-scope:
[php-scoper] 
[php-scoper] Deprecated: Return type of HumbugBox3100\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/php-scoper/.box/src/RequirementCollection.php on line 12
[php-scoper] 
[php-scoper] Deprecated: Return type of HumbugBox3100\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/php-scoper/.box/src/RequirementCollection.php on line 16
[php-scoper] 
[php-scoper] Fatal error: During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of _HumbugBox3a809f886aa2\Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/src/phpunit/tools/php-scoper/vendor/symfony/finder/Finder.php:220
[php-scoper] Stack trace:
[php-scoper] #0 phar:///usr/local/src/phpunit/tools/php-scoper/vendor/symfony/finder/Finder.php(17): _HumbugBox3a809f886aa2\Humbug\PhpScoper\{closure}(8192, 'Return type of ...', 'phar:///usr/loc...', 220)
[php-scoper] #1 phar:///usr/local/src/phpunit/tools/php-scoper/.box/vendor/composer/ClassLoader.php(444): include('phar:///usr/loc...')
[php-scoper] #2 phar:///usr/local/src/phpunit/tools/php-scoper/.box/vendor/composer/ClassLoader.php(444): include('phar:///usr/loc...')
[php-scoper] #3 phar:///usr/local/src/phpunit/tools/php-scoper/.box/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///usr/loc...')
[php-scoper] #4 [internal function]: Composer\Autoload\ClassLoader->loadClass('_HumbugBox3a809...')
[php-scoper] #5 phar:///usr/local/src/phpunit/tools/php-scoper/bin/php-scoper(42): class_alias('_HumbugBox3a809...', 'Isolated\\Symfon...')
[php-scoper] #6 /usr/local/src/phpunit/tools/php-scoper(19): require('phar:///usr/loc...')
[php-scoper] #7 /usr/local/src/phpunit/tools/php-scoper(19): require('phar:///usr/loc...')
[php-scoper] #8 {main} in phar:///usr/local/src/phpunit/tools/php-scoper/vendor/symfony/finder/Finder.php on line 17
[php-scoper] Result: 255

BUILD FAILED
/usr/local/src/phpunit/build.xml:111: The following error occurred while executing this line:
/usr/local/src/phpunit/build.xml:333: The following error occurred while executing this line:
/usr/local/src/phpunit/build.xml:391: Replace: source file /usr/local/src/phpunit/build/tmp/phar-scoped/phpunit/Util/PHP/Template/PhptTestCase.tpl doesn't exist

Total time: 2 seconds
```

**Comment by theofidry** [comment]
@sebastianbergmann I'm working on a couple of other key changes within PHP-Scoper so I probably won't be able to take a look at it before in the immediate future. I don't expect it (the 8.1 support) to be hard to add though so it will definitely be ready before 8.1 is out

**Comment by sebastianbergmann** [comment]
Thank you, @theofidry, for working on this. Once https://github.com/sebastianbergmann/phpunit/pull/4745 has been merged, PHPUnit's build will no longer fail because of this. So there is no need to rush this.

**Comment by jrfnl** [comment]
Regarding the notices coming from the Humbug Box Requirements Checker - see issue https://github.com/box-project/box/issues/567 and PR https://github.com/box-project/box/pull/568

**Comment by sebastianbergmann** [comment]
@theofidry Sorry to bother you, but PHP 8.1.0 has been tagged and will be released tomorrow. Do you have an update? Thanks!

**Comment by theofidry** [comment]
I'll try to have a look this week & next week. Not sure about how much support can be provided within this timeframe though. Unfortunately (for PHP-Scoper), I had to shift more focus on https://github.com/theofidry/AliceDataFixtures/ due to some sponsorships (goal being 8.1 support)

**Comment by mattstauffer** [comment]
@theofidry I've never worked with PHP-Scoper before, but I'm working on a PR (that relies on PRs to other repos, including `covers-validator` that will *hopefully* solve this. Fingers crossed!

**Comment by mattstauffer** [comment]
I've gotten, I think (??), everything fixed except this issue: https://github.com/box-project/box/issues/571

I'm going to push an in-progress PR and then leave that note.
