### ISSUE TITLE
SerializableClosure not found

### ISSUE THREAD

**Issue by veewee** [humbug/php-scoper#642]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.16.2
| PHP version | 8.0.x & 8.1.x
| Platform with version | MacOS
| Github Repo | https://github.com/phpro/grumphp-shim/pull/17

```
humbug/box                           3.15.0    Fast, zero config application bundler with PHARs.
humbug/php-scoper                    0.16.2    Prefixes all PHP namespaces in a file or directory.
```

When running box, I get following error:

```
./vendor/bin/box compile --working-dir='/var/folders/95/5zz8lx7j021d61k_8qpybr2r0000gn/T/grumphp-shim-build.u1ROrphj'

    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 3.15.0@8923e3c

 // Loading the configuration file
 // "/private/var/folders/95/5zz8lx7j021d61k_8qpybr2r0000gn/T/grumphp-shim-build.u1ROrphj/box.json".

PHP Fatal error:  Uncaught Error: Class "Opis\Closure\SerializableClosure" not found in /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/SimpleScoper.php:142

```

Stack trace
 
```
Stack trace:
#0 [internal function]: KevinGH\Box\PhpScoper\SimpleScoper::KevinGH\Box\PhpScoper\{closure}(Object(Closure))
#1 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/SimpleScoper.php(144): array_map(Object(Closure), Array)
#2 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/SimpleScoper.php(52): KevinGH\Box\PhpScoper\SimpleScoper::createSerializablePatchers(Object(Humbug\PhpScoper\Patcher\PatcherChain))
#3 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/Configuration.php(2848): KevinGH\Box\PhpScoper\SimpleScoper->__construct(Object(Humbug\PhpScoper\Configuration\Configuration), 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...', 'vendor/symfony/...')
#4 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/Configuration.php(1864): KevinGH\Box\Configuration\Configuration::createPhpScoperCompactor(Object(stdClass), '/private/var/fo...', Object(KevinGH\Box\Configuration\ConfigurationLogger))
#5 [internal function]: KevinGH\Box\Configuration\Configuration::KevinGH\Box\Configuration\{closure}('KevinGH\\Box\\Com...')
#6 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/Configuration.php(1869): array_map(Object(Closure), Array)
#7 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/Configuration.php(1808): KevinGH\Box\Configuration\Configuration::createCompactors(Object(stdClass), '/private/var/fo...', Array, Array, Object(KevinGH\Box\Configuration\ConfigurationLogger))
#8 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/Configuration.php(375): KevinGH\Box\Configuration\Configuration::retrieveCompactors(Object(stdClass), '/private/var/fo...', Object(KevinGH\Box\Configuration\ConfigurationLogger))
#9 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/box/src/Console/ConfigurationHelper.php(75): KevinGH\Box\Configuration\Configuration::create('/private/var/fo...', Object(stdClass))
#10 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/box/src/Console/ConfigurationLoader.php(67): KevinGH\Box\Console\ConfigurationHelper->loadFile('/private/var/fo...')
#11 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/box/src/Console/Command/ConfigurableBaseCommand.php(56): KevinGH\Box\Console\ConfigurationLoader::getConfig('/private/var/fo...', Object(KevinGH\Box\Console\ConfigurationHelper), Object(KevinGH\Box\Console\IO\IO), true)
#12 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/Compile.php(183): KevinGH\Box\Console\Command\ConfigurableBaseCommand->getConfig(Object(KevinGH\Box\Console\IO\IO), true)
#13 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/box/src/Console/Command/BaseCommand.php(42): KevinGH\Box\Console\Command\Compile->executeCommand(Object(KevinGH\Box\Console\IO\IO))
#14 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/symfony/console/Command/Command.php(298): KevinGH\Box\Console\Command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(KevinGH\Box\Console\Command\Compile), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/box/bin/box(53): Symfony\Component\Console\Application->run()
#19 /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/bin/box(117): include('/Users/verweto/...')
#20 {main}
  thrown in /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/humbug/php-scoper/vendor-hotfix/SimpleScoper.php on line 142
 ```

opis/serializable-closure is not a dependency of scoper.

After installing it manually:

```
opis/closure                         3.6.3     A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
```

I get following output from box:

```
Box version 3.15.0@8923e3c

 // Loading the configuration file
 // "/private/var/folders/95/5zz8lx7j021d61k_8qpybr2r0000gn/T/grumphp-shim-build.S3YPlnl5/box.json".

🔨  Building the PHAR "/private/var/folders/95/5zz8lx7j021d61k_8qpybr2r0000gn/T/grumphp-shim-build.S3YPlnl5/grumphp.phar"

? Registering compactors
  + KevinGH\Box\Compactor\PhpScoper
? Adding main file: /private/var/folders/95/5zz8lx7j021d61k_8qpybr2r0000gn/T/grumphp-shim-build.S3YPlnl5/bin/grumphp
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? Yes
? Exclude dev files? Yes
? Adding files

In functions.php line 32:

  Unsupported callable: Opis\Closure\ReflectionClosure::__construct(): Argument #1 ($closure) must be of type Closure, Laravel\SerializableClosure\Serializers\Native given, called in /Users/verweto/Projects/github/phpro/g
  rumphp-shim/vendor/opis/closure/src/SerializableClosure.php on line 97


In ReflectionClosure.php line 41:

  Opis\Closure\ReflectionClosure::__construct(): Argument #1 ($closure) must be of type Closure, Laravel\SerializableClosure\Serializers\Native given, called in /Users/verweto/Projects/github/phpro/grumphp-shim/vendor/opi
  s/closure/src/SerializableClosure.php on line 97
```

Commands you can run to see the result pasted above:

```
git clone https://github.com/veewee/grumphp-shim.git
cd grumphp-shim
git checkout box-3.15
composer install
make compile TAG=1.7.0 PHP=8.0
```

A Solution:
change the hotfix file to use`use Laravel\SerializableClosure\SerializableClosure;`
This works on PHP8.0 and 8.1 (if you disable deprecations)

It will fail after running box.

**Comment by theofidry** [comment]
This is weird 🤔 . Indeed opis is not a dependency of Box/PHP-Scoper. It was of Box, but has been changed in favour of the Laravel one since the latter is 8.1 compatible without FFI.

**Comment by veewee** [comment]
I don't really get how the vendor/hotfix folder works, since it is empty in version control.
But it loads a version of the SimpleScoper with opis instead of the one with laravel.

**Comment by theofidry** [comment]
Hm I thought that was fixed already. Ok I'll check out for another release on Box side

**Comment by theofidry** [comment]
Should be fixed with https://github.com/box-project/box/releases/tag/3.16.0
