### ISSUE TITLE
Return type error with PHP 8.1 

### ISSUE THREAD

**Issue by jeffreyvr** [humbug/php-scoper#649]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.16.2
| PHP version | 8.1.1
| Platform with version | macOS Monterey 12.1
| Github Repo | https://github.com/spatie/wordpress-ray/blob/master/scoper.inc.php

When running php-scoper with PHP 8.1, I run into the following error. This looks to be a PHP 8.1 compatibility issue. I have noticed that 8.1 support is being worked on, but thought it might be good to report anyway. Maybe I'm doing something wrong on my end?

Works fine when running PHP 8.0. You can find the config [here](https://github.com/spatie/wordpress-ray/blob/master/scoper.inc.php).

Output: 
```
PhpScoper version 0.16.2@9aa7488

    0/1429 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
Fatal error: During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of Humbug\PhpScoper\PhpParser\NodeVisitor\NamespaceStmt\NamespaceStmtCollection::getIterator(): iterable should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/PhpParser/NodeVisitor/NamespaceStmt/NamespaceStmtCollection.php:108
Stack trace:
#0 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/PhpParser/NodeVisitor/NamespaceStmt/NamespaceStmtCollection.php(33): Humbug\PhpScoper\{closure}(8192, 'Return type of ...', '/Users/jeffreyv...', 108)
#1 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/composer/ClassLoader.php(571): include('/Users/jeffreyv...')
#2 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/jeffreyv...')
#3 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/PhpParser/TraverserFactory.php(47): Composer\Autoload\ClassLoader->loadClass('Humbug\\PhpScope...')
#4 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/Scoper/PhpScoper.php(76): Humbug\PhpScoper\PhpParser\TraverserFactory->create(Object(Humbug\PhpScoper\Scoper\PhpScoper), 'Spatie\\WordPres...', Object(Humbug\PhpScoper\Symbol\SymbolsRegistry))
#5 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/Scoper/PhpScoper.php(65): Humbug\PhpScoper\Scoper\PhpScoper->scopePhp('<?php\n\nnamespac...')
#6 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/Scoper/PatchScoper.php(38): Humbug\PhpScoper\Scoper\PhpScoper->scope('/Users/jeffreyv...', '<?php\n\nnamespac...')
#7 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/Console/ConsoleScoper.php(203): Humbug\PhpScoper\Scoper\PatchScoper->scope('/Users/jeffreyv...', '<?php\n\nnamespac...')
#8 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/Console/ConsoleScoper.php(110): Humbug\PhpScoper\Console\ConsoleScoper->scopeFile(Object(Humbug\PhpScoper\Scoper\PatchScoper), '/Users/jeffreyv...', '<?php\n\nnamespac...', '/Users/jeffreyv...', false, Object(Humbug\PhpScoper\Console\ScoperLogger))
#9 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/Console/ConsoleScoper.php(72): Humbug\PhpScoper\Console\ConsoleScoper->scopeFiles(Object(Humbug\PhpScoper\Configuration\Configuration), '/Users/jeffreyv...', false, Object(Humbug\PhpScoper\Console\ScoperLogger))
#10 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/Console/Command/AddPrefixCommand.php(149): Humbug\PhpScoper\Console\ConsoleScoper->scope(Object(Fidry\Console\IO), Object(Humbug\PhpScoper\Configuration\Configuration), Array, '/Users/jeffreyv...', false)
#11 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/fidry/console/src/Command/SymfonyCommand.php(93): Humbug\PhpScoper\Console\Command\AddPrefixCommand->execute(Object(Fidry\Console\IO))
#12 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/symfony/console/Command/Command.php(298): Fidry\Console\Command\SymfonyCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Fidry\Console\Command\SymfonyCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/fidry/console/src/Application/ApplicationRunner.php(64): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/fidry/console/src/Application/ApplicationRunner.php(46): Fidry\Console\Application\ApplicationRunner->run(Object(Fidry\Console\IO))
#18 /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/bin/php-scoper(63): Fidry\Console\Application\ApplicationRunner::runApplication(Object(Humbug\PhpScoper\Console\Application), NULL, NULL)
#19 {main} in /Users/jeffreyvanrossum/Sites/wordpress/wp-content/plugins/wordpress-ray/vendor-bin/php-scoper/vendor/humbug/php-scoper/src/PhpParser/NodeVisitor/NamespaceStmt/NamespaceStmtCollection.php on line 33
```

**Comment by theofidry** [comment]
Indeed thanks for the report! Should be fixed in the upcoming release (it is fixed on master already)
