### ISSUE TITLE
Some Use-Statements are not scoped (Symfony/Config)

### ISSUE THREAD

**Issue by gennadigennadigennadi** [humbug/php-scoper#958]
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.18.7 (phar)
| PHP version | 8.1.25 
| Platform with version | Docker
| Github Repo | https://github.com/qossmic/deptrac-src/

<details>
 <summary>scoper.inc.php</summary>
 
 ```php
 <?php

declare(strict_types=1);

use Isolated\Symfony\Component\Finder\Finder;

$datePrefix = (new DateTimeImmutable('now'))->format('Ym');
$polyfillsBootstrap = Finder::create()
    ->files()
    ->in(__DIR__.'/vendor/symfony/polyfill-*')
    ->name('*.php');

return [
    'prefix' => 'DEPTRAC_'.$datePrefix,
    'finders' => [
        Finder::create()->files()->in([
            'config',
            'src',
            'vendor',
        ])->append([
            'bin/deptrac',
            'deptrac.config.php',
            'composer.json',
        ])->exclude([
            'bin',
            'tests',
            'test',
        ])->notName('/.*\\.(xml|md|dist|neon)|Makefile|composer\\.json|composer\\.lock/'),
    ],
    'patchers' => [],
    'tag-declarations-as-internal' => false,
    'exclude-files' => array_map(
        static function ($file) {
            return $file->getPathName();
        },
        iterator_to_array($polyfillsBootstrap)
    ),
    'exclude-namespaces' => [
        'Qossmic\Deptrac',
        'Symfony\Polyfill',
    ],
    'expose-functions' => ['trigger_deprecation'],
    'expose-global-constants' => false,
    'expose-global-classes' => false,
    'expose-global-functions' => false,
];

 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
<?php

declare(strict_types=1);

namespace Qossmic\Deptrac\Supportive\DependencyInjection;

use InvalidArgumentException;
use Qossmic\Deptrac\Contract\Config\EmitterType;
use RuntimeException;
use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

use function array_key_exists;
use function is_array;

/**
 * @psalm-suppress all
 */
class Configuration implements ConfigurationInterface
{
    /**
     * @throws InvalidArgumentException
     * @throws RuntimeException
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $builder = new TreeBuilder('deptrac');
        $rootNode = $builder->getRootNode();

        $this->appendAnalysedPaths($rootNode);
        $this->appendExcludePatterns($rootNode);
        $this->appendLayers($rootNode);
        $this->appendRuleset($rootNode);
        $this->appendSkippedViolations($rootNode);
        $this->appendFormatters($rootNode);
        $this->appendEmitterTypes($rootNode);
        $this->appendIgnoreUncoveredInternalClasses($rootNode);
        $this->appendCacheFile($rootNode);

        return $builder;
    }

    private function appendAnalysedPaths(ArrayNodeDefinition $node): void
    {
        $node
            ->fixXmlConfig('path')
            ->children()
                ->arrayNode('paths')
                    ->info('List of paths to search for PHP files to be analysed.')
                    ->addDefaultChildrenIfNoneSet()
                    ->requiresAtLeastOneElement()
                    ->scalarPrototype()
                        ->cannotBeEmpty()
                        ->defaultValue('src/')
                    ->end()
                ->end()
            ->end();
    }
...

 ```
</details>

Some Use-Statements are not getting scoped and I have no idea why. The configuration uses the `Symfony\Config` and it's not getting scoped, but just in the `configuration.php`.

Is there something obvious off with my scoper.php?

**Comment by theofidry** [comment]
@gennadigennadigennadi there is definitely something weird.

- You can double check with Box directly by doing `box process <file>` (check the help for more info)
- `tag-declarations-as-internal` is no longer valid so it indicates that you're using an old version of Box/PHP-Scoper (0.18.11 is now available)
- When I run it with Box I do see your code updated:

```
 // Loading the configuration file "/path/to/deptrac-src/box.json.dist".                                   

⚡  Processing the contents of the file /path/todeptrac-src/src/Supportive/DependencyInjection/Configuration.php

Registered replacement values:
  + @git-version@: 1.0.2-198-gfb637013

Registered compactors:
  + KevinGH\Box\Compactor\PhpScoper

Processed contents:

"""
<?php

declare (strict_types=1);
namespace Qossmic\Deptrac\Supportive\DependencyInjection;

use InvalidArgumentException;
use Qossmic\Deptrac\Contract\Config\EmitterType;
use RuntimeException;
use DEPTRAC_202403\Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use DEPTRAC_202403\Symfony\Component\Config\Definition\Builder\TreeBuilder;
use DEPTRAC_202403\Symfony\Component\Config\Definition\ConfigurationInterface;
use function array_key_exists;
use function is_array;
/**
 * @psalm-suppress all
 */
class Configuration implements ConfigurationInterface
{
    /**
     * @throws InvalidArgumentException
     * @throws RuntimeException
     */
    public function getConfigTreeBuilder() : TreeBuilder
    {
        $builder = new TreeBuilder('deptrac');
        $rootNode = $builder->getRootNode();
        $this->appendAnalysedPaths($rootNode);
        $this->appendExcludePatterns($rootNode);
        $this->appendLayers($rootNode);
        $this->appendRuleset($rootNode);
        $this->appendSkippedViolations($rootNode);
        $this->appendFormatters($rootNode);
        $this->appendEmitterTypes($rootNode);
        $this->appendIgnoreUncoveredInternalClasses($rootNode);
        $this->appendCacheFile($rootNode);
        return $builder;
    }
    private function appendAnalysedPaths(ArrayNodeDefinition $node) : void
    {
        $node->fixXmlConfig('path')->children()->arrayNode('paths')->info('List of paths to search for PHP files to be analysed.')->addDefaultChildrenIfNoneSet()->requiresAtLeastOneElement()->scalarPrototype()->cannotBeEmpty()->defaultValue('src/')->end()->end()->end();
    }
    private function appendExcludePatterns(ArrayNodeDefinition $node) : void
    {
        $node->fixXmlConfig('exclude_file')->children()->arrayNode('exclude_files')->info('List of regular expressions for excluding files or directories from being analysed')->example('#.*Test\\.php$#')->scalarPrototype()->cannotBeEmpty()->end()->end()->end();
    }
    private function appendLayers(ArrayNodeDefinition $node) : void
    {
        $node->children()->arrayNode('layers')->useAttributeAsKey('name', \false)->arrayPrototype()->children()->scalarNode('name')->isRequired()->cannotBeEmpty()->end()->arrayNode('collectors')->isRequired()->requiresAtLeastOneElement()->arrayPrototype()->ignoreExtraKeys(\false)->children()->scalarNode('type')->isRequired()->end()->variableNode('value')->end()->booleanNode('private')->defaultFalse()->end()->arrayNode('attributes')->variablePrototype()->end()->end()->end()->end()->end()->arrayNode('attributes')->variablePrototype()->end()->end()->end()->end()->end()->end();
    }
    private function appendRuleset(ArrayNodeDefinition $node) : void
    {
        $node->children()->arrayNode('ruleset')->useAttributeAsKey('name')->arrayPrototype()->scalarPrototype()->end()->end()->end()->end();
    }
    private function appendSkippedViolations(ArrayNodeDefinition $node) : void
    {
        $node->fixXmlConfig('skip_violation')->children()->arrayNode('skip_violations')->info('Skip violations matching a regular expressions')->useAttributeAsKey('name')->arrayPrototype()->scalarPrototype()->end()->end()->end()->end();
    }
    /**
     * @throws RuntimeException
     */
    private function appendFormatters(ArrayNodeDefinition $node) : void
    {
        $node->fixXmlConfig('formatter')->children()->arrayNode('formatters')->addDefaultsIfNotSet()->children()->arrayNode('graphviz')->info('Configure Graphviz output formatters')->addDefaultsIfNotSet()->children()->arrayNode('hidden_layers')->info('Specify any layer name, that you wish to exclude from the output')->scalarPrototype()->end()->end()->arrayNode('groups')->info('Combine multiple layers to a group')->useAttributeAsKey('name')->arrayPrototype()->scalarPrototype()->end()->end()->end()->booleanNode('point_to_groups')->info('When a layer is part of a group, should edges point towards the group or the layer?')->defaultFalse()->end()->end()->beforeNormalization()->ifTrue(static fn($v) => is_array($v) && array_key_exists('pointToGroups', $v))->then(static function ($v) {
            $v['point_to_groups'] = $v['pointToGroups'];
            unset($v['pointToGroups']);
            return $v;
        })->end()->end()->arrayNode('mermaidjs')->info('Configure MermaidJS output formatter')->addDefaultsIfNotSet()->children()->scalarNode('direction')->defaultValue('TD')->end()->arrayNode('groups')->info('Combine multiple layers to a group')->useAttributeAsKey('name')->arrayPrototype()->scalarPrototype()->end()->end()->end()->end()->end()->arrayNode('codeclimate')->addDefaultsIfNotSet()->info('Configure Codeclimate output formatters')->children()->arrayNode('severity')->info('Map how failures, skipped and uncovered dependencies map to severity in CodeClimate')->addDefaultsIfNotSet()->children()->enumNode('failure')->values(['info', 'minor', 'major', 'critical', 'blocker'])->defaultValue('major')->end()->enumNode('skipped')->values(['info', 'minor', 'major', 'critical', 'blocker'])->defaultValue('minor')->end()->enumNode('uncovered')->values(['info', 'minor', 'major', 'critical', 'blocker'])->defaultValue('info')->end()->end()->end()->end()->end()->end()->end()->end();
    }
    /**
     * @throws InvalidArgumentException
     * @throws RuntimeException
     */
    private function appendEmitterTypes(ArrayNodeDefinition $node) : void
    {
        $node->children()->arrayNode('analyser')->addDefaultsIfNotSet()->children()->scalarNode('internal_tag')->defaultNull()->end()->arrayNode('types')->defaultValue([EmitterType::CLASS_TOKEN->value, EmitterType::FUNCTION_TOKEN->value])->scalarPrototype()->beforeNormalization()->ifNotInArray(EmitterType::values())->thenInvalid('Invalid type %s')->end()->end()->end()->end()->end()->end();
    }
    private function appendIgnoreUncoveredInternalClasses(ArrayNodeDefinition $node) : void
    {
        $node->children()->booleanNode('ignore_uncovered_internal_classes')->defaultTrue()->end()->end();
    }
    private function appendCacheFile(ArrayNodeDefinition $node) : void
    {
        $node->children()->scalarNode('cache_file')->defaultValue('.deptrac.cache')->end()->end();
    }
}

"""

Symbols Registry:

"""
Humbug\PhpScoper\Symbol\SymbolsRegistry {#320
  -recordedFunctions: []
  -recordedClasses: []
}

"""

```

Note that the namespace is not changed because `Qossmic\Deptrac` is an excluded namespace.

**Comment by gennadigennadigennadi** [comment]
```sh
❯ build/php-scoper.phar inspect src/Supportive/DependencyInjection/Configuration.php

Scopped contents:

"""
<?php

declare (strict_types=1);
namespace Qossmic\Deptrac\Supportive\DependencyInjection;

use InvalidArgumentException;
use Qossmic\Deptrac\Contract\Config\EmitterType;
use RuntimeException;
use DEPTRAC_202403\Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use DEPTRAC_202403\Symfony\Component\Config\Definition\Builder\TreeBuilder;
use DEPTRAC_202403\Symfony\Component\Config\Definition\ConfigurationInterface;
use function array_key_exists;
use function is_array;
/**
 * @psalm-suppress all
 */
class Configuration implements ConfigurationInterface
{
    /**
     * @throws InvalidArgumentException
     * @throws RuntimeException
     */
    public function getConfigTreeBuilder() : TreeBuilder
    {
        $builder = new TreeBuilder('deptrac');
        $rootNode = $builder->getRootNode();
        $this->appendAnalysedPaths($rootNode);
        $this->appendExcludePatterns($rootNode);
        $this->appendLayers($rootNode);
        $this->appendRuleset($rootNode);
        $this->appendSkippedViolations($rootNode);
        $this->appendFormatters($rootNode);
        $this->appendEmitterTypes($rootNode);
        $this->appendIgnoreUncoveredInternalClasses($rootNode);
        return $builder;
    }
    private function appendAnalysedPaths(ArrayNodeDefinition $node) : void
    {
        $node->fixXmlConfig('path')->children()->arrayNode('paths')->info('List of paths to search for PHP files to be analysed.')->addDefaultChildrenIf
NoneSet()->requiresAtLeastOneElement()->scalarPrototype()->cannotBeEmpty()->defaultValue('src/')->end()->end()->end();
    }
    private function appendExcludePatterns(ArrayNodeDefinition $node) : void
    {
        $node->fixXmlConfig('exclude_file')->children()->arrayNode('exclude_files')->info('List of regular expressions for excluding files or directorie
s from being analysed')->example('#.*Test\\.php$#')->scalarPrototype()->cannotBeEmpty()->end()->end()->end();
    }
    private function appendLayers(ArrayNodeDefinition $node) : void
    {
        $node->children()->arrayNode('layers')->useAttributeAsKey('name', \false)->arrayPrototype()->children()->scalarNode('name')->isRequired()->canno
tBeEmpty()->end()->arrayNode('collectors')->isRequired()->requiresAtLeastOneElement()->arrayPrototype()->ignoreExtraKeys(\false)->children()->scalarNode
('type')->isRequired()->end()->variableNode('value')->end()->booleanNode('private')->defaultFalse()->end()->arrayNode('attributes')->variablePrototype()
->end()->end()->end()->end()->end()->arrayNode('attributes')->variablePrototype()->end()->end()->end()->end()->end()->end();
    }
    private function appendRuleset(ArrayNodeDefinition $node) : void
    {
        $node->children()->arrayNode('ruleset')->useAttributeAsKey('name')->arrayPrototype()->scalarPrototype()->end()->end()->end()->end();
    }
    private function appendSkippedViolations(ArrayNodeDefinition $node) : void
    {
        $node->fixXmlConfig('skip_violation')->children()->arrayNode('skip_violations')->info('Skip violations matching a regular expressions')->useAttr
ibuteAsKey('name')->arrayPrototype()->scalarPrototype()->end()->end()->end()->end();
    }
    /**
     * @throws RuntimeException
     */
    private function appendFormatters(ArrayNodeDefinition $node) : void
    {
        $node->fixXmlConfig('formatter')->children()->arrayNode('formatters')->addDefaultsIfNotSet()->children()->arrayNode('graphviz')->info('Configure
 Graphviz output formatters')->addDefaultsIfNotSet()->children()->arrayNode('hidden_layers')->info('Specify any layer name, that you wish to exclude fro
m the output')->scalarPrototype()->end()->end()->arrayNode('groups')->info('Combine multiple layers to a group')->useAttributeAsKey('name')->arrayProtot
ype()->scalarPrototype()->end()->end()->end()->booleanNode('point_to_groups')->info('When a layer is part of a group, should edges point towards the gro
up or the layer?')->defaultFalse()->end()->end()->beforeNormalization()->ifTrue(static fn($v) => is_array($v) && array_key_exists('pointToGroups', $v))-
>then(static function ($v) {
            $v['point_to_groups'] = $v['pointToGroups'];
            unset($v['pointToGroups']);
            return $v;
        })->end()->end()->arrayNode('mermaidjs')->info('Configure MermaidJS output formatter')->addDefaultsIfNotSet()->children()->scalarNode('direction
')->defaultValue('TD')->end()->arrayNode('groups')->info('Combine multiple layers to a group')->useAttributeAsKey('name')->arrayPrototype()->scalarProto
type()->end()->end()->end()->end()->end()->arrayNode('codeclimate')->addDefaultsIfNotSet()->info('Configure Codeclimate output formatters')->children()-
>arrayNode('severity')->info('Map how failures, skipped and uncovered dependencies map to severity in CodeClimate')->addDefaultsIfNotSet()->children()->
enumNode('failure')->values(['info', 'minor', 'major', 'critical', 'blocker'])->defaultValue('major')->end()->enumNode('skipped')->values(['info', 'mino
r', 'major', 'critical', 'blocker'])->defaultValue('minor')->end()->enumNode('uncovered')->values(['info', 'minor', 'major', 'critical', 'blocker'])->de
faultValue('info')->end()->end()->end()->end()->end()->end()->end()->end();
    }
    /**
     * @throws InvalidArgumentException
     * @throws RuntimeException
     */
    private function appendEmitterTypes(ArrayNodeDefinition $node) : void
    {
        $node->children()->arrayNode('analyser')->addDefaultsIfNotSet()->children()->scalarNode('internal_tag')->defaultNull()->end()->arrayNode('types'
)->defaultValue([EmitterType::CLASS_TOKEN->value, EmitterType::FUNCTION_TOKEN->value])->scalarPrototype()->beforeNormalization()->ifNotInArray(EmitterTy
pe::values())->thenInvalid('Invalid type %s')->end()->end()->end()->end()->end()->end();
    }
    private function appendIgnoreUncoveredInternalClasses(ArrayNodeDefinition $node) : void
    {
        $node->children()->booleanNode('ignore_uncovered_internal_classes')->defaultTrue()->end()->end();
    }
}

"""

Fatal error: Uncaught Error: Class "_HumbugBox7785008de33b\Symfony\Component\VarDumper\Cloner\VarCloner" not found in phar:///home/gennadi/Code/qossmic/
deptrac-src/build/php-scoper.phar/src/Console/Command/InspectCommand.php:99
Stack trace:
#0 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/src/Console/Command/InspectCommand.php(94): _HumbugBox7785008de33b\Humbug\PhpScop
er\Console\Command\InspectCommand::exportSymbolsRegistry(Object(_HumbugBox7785008de33b\Humbug\PhpScoper\Symbol\SymbolsRegistry), Object(_HumbugBox778500
8de33b\Fidry\Console\Input\IO))
#1 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/src/Console/Command/InspectCommand.php(58): _HumbugBox7785008de33b\Humbug\PhpScop
er\Console\Command\InspectCommand->printScoppedContents(Object(_HumbugBox7785008de33b\Fidry\Console\Input\IO), '<?php\n\ndeclare ...', Object(_HumbugBox
7785008de33b\Humbug\PhpScoper\Symbol\SymbolsRegistry))
#2 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/v
umbug\PhpScoper\Console\Command\InspectCommand->execute(Object(_HumbugBo
#3 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/v
sole\Command\SymfonyCommand->execute(Object(_HumbugBox7785008de33b\Symfo
ponent\Console\Output\ConsoleOutput))
#4 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/v
nent\Console\Command\Command->run(Object(_HumbugBox7785008de33b\Symfony\
ent\Console\Output\ConsoleOutput))
#5 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/v
nent\Console\Application->doRunCommand(Object(_HumbugBox7785008de33b\Fid
ent\Console\Input\ArgvInput), Object(_HumbugBox7785008de33b\Symfony\Comp
#6 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/v
nent\Console\Application->doRun(Object(_HumbugBox7785008de33b\Symfony\Co
t\Console\Output\ConsoleOutput))
#7 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/v
de33b\Symfony\Component\Console\Application->run(Object(_HumbugBox778500
\Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/v
de33b\Fidry\Console\Application\ApplicationRunner->run(Object(_HumbugBox
#9 phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar/b
unner::runApplication(Object(_HumbugBox7785008de33b\Humbug\PhpScoper\Con
#10 /home/gennadi/Code/qossmic/deptrac-src/build/php-scoper.phar(19): re
#11 {main}
  thrown in phar:///home/gennadi/Code/qossmic/deptrac-src/build/php-scop

deptrac-src (842a8c6) [!] via 🐘 v8.3.3 
❯ 
```

Thats the output I get. I clains to scoped the symfony code but the real output still leaves them out. But there is that Fatal Error, maybe thats the real cause?

**Comment by gennadigennadigennadi** [comment]
I updated my docker container php8.1 -> php8.3 and now I get a correctly scoped `configuration.php`.

@theofidry thank you for your help.
